spring:
  data:
    mongodb:
      uri: mongodb+srv://rokin:Rokin123@cluster0.v1blj.mongodb.net/myFirstDatabase?retryWrites=true&w=majority

twitter:
  consumer:
    key: PmuzfCss7EzS8T5e2ezN8SuUO
    secret: i1r55PzmhUA0e0ZVw5n3UIE0yydHIX9RhzBzMVzlRoodwhapNX
  access:
    token: 3112974903-CLlBLgwqP9Mjxb5KtBZa63wBOU1MCWXpUhGmcVd
    secret: 8BUZz48xWyFWyfQFGPDVIiCY0jnyO3hEKDKGqLIDKSE5P
    
